# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/spd1000x_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 557)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/spd_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 10, 331, 161))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(4)
        self.lcdNumber.setObjectName("lcdNumber")
        self.oLcdVoltIn0 = QtWidgets.QLCDNumber(self.centralwidget)
        self.oLcdVoltIn0.setGeometry(QtCore.QRect(40, 460, 31, 51))
        self.oLcdVoltIn0.setSmallDecimalPoint(False)
        self.oLcdVoltIn0.setDigitCount(1)
        self.oLcdVoltIn0.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.oLcdVoltIn0.setObjectName("oLcdVoltIn0")
        self.oDialCurr = QtWidgets.QDial(self.centralwidget)
        self.oDialCurr.setGeometry(QtCore.QRect(220, 350, 111, 111))
        self.oDialCurr.setMaximum(9)
        self.oDialCurr.setSingleStep(1)
        self.oDialCurr.setPageStep(1)
        self.oDialCurr.setInvertedAppearance(False)
        self.oDialCurr.setInvertedControls(False)
        self.oDialCurr.setWrapping(False)
        self.oDialCurr.setNotchTarget(5.0)
        self.oDialCurr.setNotchesVisible(True)
        self.oDialCurr.setObjectName("oDialCurr")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 50, 90, 90))
        self.label.setMaximumSize(QtCore.QSize(90, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/red.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 180, 331, 161))
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setDigitCount(4)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(370, 450, 81, 51))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 190, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.oDialVolt = QtWidgets.QDial(self.centralwidget)
        self.oDialVolt.setGeometry(QtCore.QRect(40, 350, 111, 111))
        self.oDialVolt.setAcceptDrops(False)
        self.oDialVolt.setMaximum(9)
        self.oDialVolt.setPageStep(1)
        self.oDialVolt.setTracking(True)
        self.oDialVolt.setWrapping(False)
        self.oDialVolt.setNotchTarget(5.0)
        self.oDialVolt.setNotchesVisible(True)
        self.oDialVolt.setObjectName("oDialVolt")
        self.oLcdVoltIn1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.oLcdVoltIn1.setGeometry(QtCore.QRect(70, 460, 31, 51))
        self.oLcdVoltIn1.setSmallDecimalPoint(False)
        self.oLcdVoltIn1.setDigitCount(1)
        self.oLcdVoltIn1.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.oLcdVoltIn1.setObjectName("oLcdVoltIn1")
        self.oLcdVoltIn2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.oLcdVoltIn2.setGeometry(QtCore.QRect(100, 460, 31, 51))
        self.oLcdVoltIn2.setSmallDecimalPoint(False)
        self.oLcdVoltIn2.setDigitCount(1)
        self.oLcdVoltIn2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.oLcdVoltIn2.setObjectName("oLcdVoltIn2")
        self.oLcdVoltIn3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.oLcdVoltIn3.setGeometry(QtCore.QRect(130, 460, 31, 51))
        self.oLcdVoltIn3.setSmallDecimalPoint(False)
        self.oLcdVoltIn3.setDigitCount(1)
        self.oLcdVoltIn3.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.oLcdVoltIn3.setObjectName("oLcdVoltIn3")
        self.oLcdCurrIn2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.oLcdCurrIn2.setGeometry(QtCore.QRect(290, 460, 31, 51))
        self.oLcdCurrIn2.setSmallDecimalPoint(False)
        self.oLcdCurrIn2.setDigitCount(1)
        self.oLcdCurrIn2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.oLcdCurrIn2.setObjectName("oLcdCurrIn2")
        self.oLcdCurrIn0 = QtWidgets.QLCDNumber(self.centralwidget)
        self.oLcdCurrIn0.setGeometry(QtCore.QRect(230, 460, 31, 51))
        self.oLcdCurrIn0.setSmallDecimalPoint(False)
        self.oLcdCurrIn0.setDigitCount(1)
        self.oLcdCurrIn0.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.oLcdCurrIn0.setObjectName("oLcdCurrIn0")
        self.oLcdCurrIn1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.oLcdCurrIn1.setGeometry(QtCore.QRect(260, 460, 31, 51))
        self.oLcdCurrIn1.setSmallDecimalPoint(False)
        self.oLcdCurrIn1.setDigitCount(1)
        self.oLcdCurrIn1.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.oLcdCurrIn1.setObjectName("oLcdCurrIn1")
        self.oButVoltSel = QtWidgets.QPushButton(self.centralwidget)
        self.oButVoltSel.setGeometry(QtCore.QRect(80, 389, 31, 31))
        self.oButVoltSel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 15px;")
        self.oButVoltSel.setText("")
        self.oButVoltSel.setObjectName("oButVoltSel")
        self.oButCurrSel = QtWidgets.QPushButton(self.centralwidget)
        self.oButCurrSel.setGeometry(QtCore.QRect(260, 389, 31, 31))
        self.oButCurrSel.setStyleSheet("border: 2px solid black;\n"
"border-radius: 15px;")
        self.oButCurrSel.setText("")
        self.oButCurrSel.setDefault(False)
        self.oButCurrSel.setObjectName("oButCurrSel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 21))
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.oMenu = QtWidgets.QMenu(self.menubar)
        self.oMenu.setObjectName("oMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.oActExit = QtWidgets.QAction(MainWindow)
        self.oActExit.setObjectName("oActExit")
        self.oActAbout = QtWidgets.QAction(MainWindow)
        self.oActAbout.setObjectName("oActAbout")
        self.menuInfo.addAction(self.oActAbout)
        self.oMenu.addAction(self.oActExit)
        self.menubar.addAction(self.oMenu.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.oMenu.setTitle(_translate("MainWindow", "Edit"))
        self.oActExit.setText(_translate("MainWindow", "Exit"))
        self.oActAbout.setText(_translate("MainWindow", "About"))

import ui_res_rc
